In [23]:
a=(('Cong Truong',), ('Canteen',), ('A3',))

In [27]:
a[1][0]

'Canteen'

In [19]:
len(a)

2

In [1]:
with open("url_cam.txt") as f:
    lines=f.readlines()

In [2]:
lines

['http://192.168.1.4/cam-lo.jpg\n', 'http://192.168.1.2/cam-lo.jpg']

In [1]:
import os

parent_dir = os.getcwd()
parent_dir

'd:\\PTIT\\IoT\\d\\project'

In [26]:
from datetime import timedelta, datetime

filename = str(datetime.now())
specialChars = "!#$%^&*():.- "
for specialChar in specialChars:
    filename = filename.replace(specialChar, '')

In [27]:
filename

'20221109215528840454'

In [28]:
# import datetime

In [30]:
datetime.now()

datetime.datetime(2022, 11, 9, 21, 55, 38, 868378)

In [21]:
datetime.timedelta(minutes=1)

datetime.timedelta(seconds=60)

In [23]:
datetime.today()

AttributeError: module 'datetime' has no attribute 'today'

In [36]:
time=str(datetime.now())

In [37]:
time

'2022-11-09 22:10:06.135552'

In [1]:
import cv2
import numpy as np
from cv2 import dnn
from numpy.lib.type_check import imag
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.python.framework.ops import device
import tensorflow as tf
import base64
from datetime import datetime
import urllib.request
from tensorflow.keras.preprocessing import image
import numpy as np
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img , img_to_array

c:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
from imutils.video import WebcamVideoStream
from imutils.video import FPS

In [3]:
classes = ['Box_cardboard_paper', 'glass_metal_plastic', 'organic', 'other']
img_file=r"D:\PTIT\IoT\d\project\static\images\bottle.jpg"
model = load_model("D:\PTIT\IoT\d\project\detect\model_mobinetv2_35_epoch.h5")


In [4]:
def process_image(img_path):
  img = load_img(img_path, target_size=(224, 224))
  img_array = img_to_array(img)
  
  img_array = np.expand_dims(img_array, axis=0)
  pImg = preprocess_input(img_array)
  return pImg


In [5]:
print(process_image(img_file))

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]


In [26]:
import pandas as pd
import json

In [30]:
df=pd.read_excel(r"D:\PTIT\IoT\d\project\Book1.xlsx")

In [31]:
df

sl                label         time
0   1  box_cardboard_paper  "11/1/2022"
1  20              organic  "11/1/2022"
2   1  box_cardboard_paper  "11/2/2022"
3  40  glass_metal_plastic  "11/2/2022"
4   1  box_cardboard_paper  "11/3/2022"

In [32]:
newjson=df.to_json(orient="records")
js=json.loads(newjson)

In [33]:
js[0]['time']

'"11/1/2022"'

In [34]:
newjson

'[{"sl":1,"label":"box_cardboard_paper","time":"\\"11\\/1\\/2022\\""},{"sl":20,"label":"organic","time":"\\"11\\/1\\/2022\\""},{"sl":1,"label":"box_cardboard_paper","time":"\\"11\\/2\\/2022\\""},{"sl":40,"label":"glass_metal_plastic","time":"\\"11\\/2\\/2022\\""},{"sl":1,"label":"box_cardboard_paper","time":"\\"11\\/3\\/2022\\""}]'

In [35]:
a=((1,2,3),(4,5,6))

In [36]:
a[1]

(4, 5, 6)

In [38]:
for i in a:
    print(i[0])

1
4


In [2]:
import cv2

In [3]:
img=cv2.imread('static/images/2022-11-17/20221117180503332914.jpg')


In [4]:
cv2.imshow("hehe",img)

In [5]:
cv2.imwrite("l",img)

error: OpenCV(4.6.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:730: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'


: 

In [3]:
from datetime import datetime

label='box_cardboard_paper'
url='/home/hauuu/Desktop/IoT/detect/dataset/'+label
time=str(datetime.now())
file_name=url+"/"+time+".jpg"
print(file_name)

/home/hauuu/Desktop/IoT/detect/dataset/box_cardboard_paper/2022-11-18 14:58:17.658993.jpg
